std_msgs/Header header                         #frame header information
bool isline                                    #True if there is a line
int64 id                                       #line number
float32[] metric_start                         #line starting point in meters
float32[] pixel_start                          #line starting point in pixels
int64 start_w                                  #starting point vector width
int64 start_h                                  #starting point vector height

float32[] metric_end                           #line ending point in meters
float32[] pixel_end                            #line ending point in pixels
int64 end_w                                    #ending point vector width
int64 end_h                                    #ending point vector height

