std_msgs/Header header                         #frame header information
bool ispoint                                   #True if there is a point
int64 id                                       #point number
float32[] metric_point                         #point in meters [x_depth, y_width, z_height]
float32[] pixel_point                          #point in pixels
int64 point_w                                  #point vector width
int64 point_h                                  #point vector height
